version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    networks:
      - mysql-compose-network
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: root

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

  app:
    container_name: api-svc
    build: .
    ports:
        - "3000:3000"
    environment:
      TYPEORM_HOST: db
      TYPEORM_USERNAME: root
      TYPEORM_PASSWORD: root
      TYPEORM_DATABASE: todo
      TYPEORM_PORT: 3306
      TYPEORM_MIGRATIONS: src/migrations/**/*.ts
      NODE_ENV: prod
      PORT: 3000
    entrypoint:
      - npm
      - run
      - start:prod
    links:
      - db
    depends_on:
      - db
    networks:
      - mysql-compose-network
networks: 
  mysql-compose-network:
    driver: bridge